# Generated by Django 3.1.1 on 2020-10-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='subCategorias',
            new_name='subategorias',
        ),
    ]
