# Generated by Django 3.1.1 on 2020-10-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20201016_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='productos',
        ),
    ]
