# Generated by Django 3.1.1 on 2020-10-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20201016_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='subcategorias',
            field=models.ManyToManyField(to='productos.Subcategoria'),
        ),
    ]
