# Generated by Django 3.1.1 on 2020-10-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20201016_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idMarca',
            new_name='marca',
        ),
    ]
