# Generated by Django 3.1.1 on 2020-11-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20201016_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.CharField(max_length=30)),
                ('ruc', models.CharField(max_length=10)),
            ],
        ),
    ]
