# Generated by Django 3.1.1 on 2020-11-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_empresaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=16)),
                ('minimoAplicable', models.DecimalField(decimal_places=2, max_digits=16)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
    ]
