# Generated by Django 3.1.1 on 2020-11-06 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_cupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Carrito', 'CARRITO'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Orden Cerrada', 'ORDEN CERRADA')], default='Carrito', max_length=25)),
                ('no_Orden', models.CharField(max_length=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('envio', models.DecimalField(decimal_places=2, max_digits=16)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('idcupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.cupon')),
            ],
        ),
    ]
