# Generated by Django 3.1.1 on 2020-11-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_producto_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('clave', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='imagen',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
    ]
