# Generated by Django 3.1.1 on 2020-11-20 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20201119_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'CARRITO'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Orden Cerrada', 'ORDEN CERRADA')], default='Carrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='orden',
            name='idcupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.cupon'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('activo', models.BooleanField()),
                ('direccion', models.CharField(max_length=200)),
                ('idLogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.login')),
            ],
        ),
    ]
