# Generated by Django 3.1.1 on 2020-11-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_auto_20201119_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='idCliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO'), ('Orden Cerrada', 'ORDEN CERRADA')], default='Carrito', max_length=25),
        ),
    ]
