# Generated by Django 3.1.1 on 2020-11-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_auto_20201119_1826'),
        ('productos', '0012_auto_20201119_0324'),
    ]

    operations = [
    ]
