# Generated by Django 3.1.1 on 2020-11-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_merge_20201120_1735'),
        ('productos', '0016_auto_20201121_1146'),
    ]

    operations = [
    ]
