# Generated by Django 3.1.1 on 2020-11-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_auto_20201121_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Cerrada', 'ORDEN CERRADA'), ('Carrito', 'CARRITO'), ('En Proceso', 'EN PROCESO'), ('Orden Abierta', 'ORDEN ABIERTA')], default='Carrito', max_length=25),
        ),
    ]
