# Generated by Django 3.1.1 on 2020-11-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_auto_20201121_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Cerrada', 'ORDEN CERRADA'), ('En Proceso', 'EN PROCESO'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
    ]
