# Generated by Django 3.1.1 on 2020-11-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_auto_20201121_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'EN PROCESO'), ('Carrito', 'CARRITO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA')], default='Carrito', max_length=25),
        ),
    ]
