# Generated by Django 3.1.1 on 2020-11-22 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0027_auto_20201121_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='orden',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'EN PROCESO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
    ]
