# Generated by Django 3.1.1 on 2020-11-22 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0029_auto_20201121_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='envio',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA'), ('En Proceso', 'EN PROCESO'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='orden',
            name='no_Orden',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
