# Generated by Django 3.1.1 on 2020-11-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0030_auto_20201121_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Cerrada', 'ORDEN CERRADA'), ('En Proceso', 'EN PROCESO'), ('Carrito', 'CARRITO'), ('Orden Abierta', 'ORDEN ABIERTA')], default='Carrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto_orden',
            name='idOrden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.orden'),
        ),
        migrations.AlterField(
            model_name='producto_orden',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
