# Generated by Django 3.1.1 on 2020-11-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0031_auto_20201122_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Abierta', 'ORDEN ABIERTA'), ('En Proceso', 'EN PROCESO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
    ]
