# Generated by Django 3.1.1 on 2020-11-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0032_auto_20201126_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO'), ('En Proceso', 'EN PROCESO')], default='Carrito', max_length=25),
        ),
    ]
