# Generated by Django 3.1.1 on 2020-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0032_auto_20201126_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.ManyToManyField(to='productos.Tags'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Cerrada', 'ORDEN CERRADA'), ('En Proceso', 'EN PROCESO'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
    ]
