# Generated by Django 3.1.1 on 2020-11-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0034_auto_20201129_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tags',
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'CARRITO'), ('En Proceso', 'EN PROCESO'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Orden Cerrada', 'ORDEN CERRADA')], default='Carrito', max_length=25),
        ),
    ]
