# Generated by Django 3.1.1 on 2020-12-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0036_auto_20201129_1242'),
        ('productos', '0033_auto_20201127_1604'),
    ]

    operations = [
    ]
