# Generated by Django 3.1.1 on 2020-12-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0037_merge_20201206_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('En Proceso', 'EN PROCESO')], default='Carrito', max_length=25),
        ),
    ]
