# Generated by Django 3.1.1 on 2020-12-07 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0038_auto_20201206_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_orden',
            name='idEmpresa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='productos.empresa'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Abierta', 'ORDEN ABIERTA'), ('Orden Cerrada', 'ORDEN CERRADA'), ('En Proceso', 'EN PROCESO'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
    ]
