# Generated by Django 3.1.1 on 2020-12-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0039_auto_20201206_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_orden',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'CARRITO'), ('En Proceso', 'EN PROCESO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA')], default='Carrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'CARRITO'), ('En Proceso', 'EN PROCESO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA')], default='Carrito', max_length=25),
        ),
    ]
