# Generated by Django 3.1.1 on 2020-12-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0042_auto_20201207_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='direccion',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'CARRITO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA'), ('En Proceso', 'EN PROCESO')], default='Carrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto_orden',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'CARRITO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA'), ('En Proceso', 'EN PROCESO')], default='Carrito', max_length=25),
        ),
    ]
