# Generated by Django 3.1.1 on 2020-12-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0043_auto_20201207_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'EN PROCESO'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto_orden',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'EN PROCESO'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='producto_orden',
            unique_together={('idEmpresa', 'idProducto', 'idOrden')},
        ),
    ]
