# Generated by Django 3.1.1 on 2020-12-09 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0044_auto_20201207_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_orden',
            name='tamanio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.talla'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Abierta', 'ORDEN ABIERTA'), ('En Proceso', 'EN PROCESO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto_orden',
            name='estado',
            field=models.CharField(choices=[('Orden Abierta', 'ORDEN ABIERTA'), ('En Proceso', 'EN PROCESO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
    ]
