# Generated by Django 3.1.1 on 2020-12-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0044_auto_20201207_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'EN PROCESO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto_orden',
            name='estado',
            field=models.CharField(choices=[('En Proceso', 'EN PROCESO'), ('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO')], default='Carrito', max_length=25),
        ),
    ]
