# Generated by Django 3.1.1 on 2020-12-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0046_auto_20201208_2109'),
        ('productos', '0046_auto_20201207_2243'),
    ]

    operations = [
    ]
