# Generated by Django 3.1.1 on 2020-12-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0047_merge_20201209_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO'), ('En Proceso', 'EN PROCESO')], default='Carrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto_orden',
            name='estado',
            field=models.CharField(choices=[('Orden Cerrada', 'ORDEN CERRADA'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Carrito', 'CARRITO'), ('En Proceso', 'EN PROCESO')], default='Carrito', max_length=25),
        ),
    ]
