# Generated by Django 3.1.1 on 2020-12-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0048_auto_20201209_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'CARRITO'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Orden Cerrada', 'ORDEN CERRADA'), ('En Proceso', 'EN PROCESO')], default='Carrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto_orden',
            name='estado',
            field=models.CharField(choices=[('Carrito', 'CARRITO'), ('Orden Abierta', 'ORDEN ABIERTA'), ('Orden Cerrada', 'ORDEN CERRADA'), ('En Proceso', 'EN PROCESO')], default='Carrito', max_length=25),
        ),
    ]
