# Generated by Django 3.1.1 on 2020-11-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201121_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
